# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53735bd4a229be1c6321229bd50e3a48ce0732e0f35f714761faba5ff0e7b53b879c8fadc882bc5e38d88f9cce0f92834b6f83345f60ca1de5db320e84bc3c82

test:
  secret_key_base: 62484a18a0b28841325a1c9e9c8d7e73a63abae6707fd5a92652d39b7722aa493baf7293af3bcdb9db212df2b1a747c76c4cb335754cbbfc60128b22879d56af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
